-- Tenants and the usage ledger.

CREATE TABLE tenants (
    id           VARCHAR(64)  PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    -- SHA-256 hex of the API key. Plaintext keys are never stored, so a database
    -- dump does not hand over working credentials.
    --
    -- VARCHAR rather than CHAR even though the length is fixed: Postgres pads CHAR
    -- with spaces, which silently breaks equality against an unpadded lookup value.
    api_key_hash VARCHAR(64)  NOT NULL UNIQUE,
    -- Tokens per budget period. 0 means "use the configured default".
    token_limit  BIGINT       NOT NULL DEFAULT 0 CHECK (token_limit >= 0),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Append-only record of what every served request cost.
--
-- A ledger rather than a running total on the tenant row: totals can always be
-- derived from the ledger, but the ledger cannot be recovered from a total. Keeping
-- the rows is what makes per-model cost attribution, usage disputes and
-- retrospective budget changes answerable at all.
CREATE TABLE usage_records (
    -- Identity column rather than BIGSERIAL: it is the SQL-standard spelling and
    -- matches the entity's GenerationType.IDENTITY.
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         VARCHAR(64) NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    provider          VARCHAR(64) NOT NULL,
    model             VARCHAR(128) NOT NULL,
    prompt_tokens     INTEGER     NOT NULL CHECK (prompt_tokens >= 0),
    completion_tokens INTEGER     NOT NULL CHECK (completion_tokens >= 0),
    -- Cache hits cost no upstream tokens and are excluded from budget sums.
    cache_hit         BOOLEAN     NOT NULL DEFAULT FALSE,
    latency_ms        BIGINT      NOT NULL CHECK (latency_ms >= 0),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Every budget check is "sum tokens for this tenant since T", so the index leads
-- with tenant and then time. A partial index on cache_hit = false would be tempting,
-- but cache hits are a minority of rows and the composite index already answers the
-- query with an index-only scan on most plans.
CREATE INDEX idx_usage_tenant_time ON usage_records (tenant_id, created_at DESC);

-- Demo tenants, so the gateway is usable the moment it starts.
--
-- These keys are published in the README and are for local demos only. Anything
-- deployed anywhere real must delete these rows; they are intentionally obvious
-- rather than looking like credentials someone might mistake for real ones.
INSERT INTO tenants (id, name, api_key_hash, token_limit) VALUES
    ('demo-free',     'Demo — free tier',
     'a3a394b9b0f39889569938a699d7182d41c3cb211d9475fd09fc98b5e1fe8516', 5000),
    ('demo-pro',      'Demo — pro tier',
     '7b340101426eaa6810ee547503b923bfd895a40cd62b1e52686bf8ffaa8d6e36', 500000),
    ('demo-internal', 'Demo — internal',
     '9b58a7b3d1de010f751796647619bd70b075eb49e16e615103d361876a3728f9', 10000000);
